<?php
/**
 * Shared helpers: configuration, stops/lines database access, text normalization.
 *
 * Data files (generated by scripts/preprocess_data.php):
 *   data/stops.json : { "<stopId>": [name, city, [lineId, ...], searchText], ... }
 *   data/lines.json : { "<lineId>": "<line short name>", ... }
 */

define('APP_ROOT', dirname(__DIR__));

/**
 * Load configuration: config.php (gitignored) overrides config.sample.php defaults,
 * environment variable PRIM_API_KEY overrides both.
 */
function app_config()
{
    static $config = null;
    if ($config !== null) {
        return $config;
    }
    $config = require APP_ROOT . '/config.sample.php';
    if (is_file(APP_ROOT . '/config.php')) {
        $local = require APP_ROOT . '/config.php';
        if (is_array($local)) {
            $config = array_merge($config, $local);
        }
    }
    $env = getenv('PRIM_API_KEY');
    if ($env) {
        $config['prim_api_key'] = $env;
    }
    return $config;
}

/** @return array<string, array> stops database */
function load_stops()
{
    static $stops = null;
    if ($stops === null) {
        $stops = json_decode(file_get_contents(APP_ROOT . '/data/stops.json'), true);
        if (!is_array($stops)) {
            $stops = array();
        }
    }
    return $stops;
}

/** @return array<string, string> lines database (id => short name) */
function load_lines()
{
    static $lines = null;
    if ($lines === null) {
        $lines = json_decode(file_get_contents(APP_ROOT . '/data/lines.json'), true);
        if (!is_array($lines)) {
            $lines = array();
        }
    }
    return $lines;
}

/**
 * Lowercase, strip accents, replace non letters by spaces.
 * Pure PHP (no intl / iconv dependency) so it behaves the same on any hosting.
 */
function normalize_search($text)
{
    static $map = array(
        'à' => 'a', 'á' => 'a', 'â' => 'a', 'ã' => 'a', 'ä' => 'a', 'å' => 'a',
        'ç' => 'c', 'è' => 'e', 'é' => 'e', 'ê' => 'e', 'ë' => 'e',
        'ì' => 'i', 'í' => 'i', 'î' => 'i', 'ï' => 'i', 'ñ' => 'n',
        'ò' => 'o', 'ó' => 'o', 'ô' => 'o', 'õ' => 'o', 'ö' => 'o', 'ø' => 'o',
        'ù' => 'u', 'ú' => 'u', 'û' => 'u', 'ü' => 'u', 'ý' => 'y', 'ÿ' => 'y',
        'À' => 'a', 'Á' => 'a', 'Â' => 'a', 'Ã' => 'a', 'Ä' => 'a', 'Å' => 'a',
        'Ç' => 'c', 'È' => 'e', 'É' => 'e', 'Ê' => 'e', 'Ë' => 'e',
        'Ì' => 'i', 'Í' => 'i', 'Î' => 'i', 'Ï' => 'i', 'Ñ' => 'n',
        'Ò' => 'o', 'Ó' => 'o', 'Ô' => 'o', 'Õ' => 'o', 'Ö' => 'o', 'Ø' => 'o',
        'Ù' => 'u', 'Ú' => 'u', 'Û' => 'u', 'Ü' => 'u', 'Ý' => 'y',
        'œ' => 'oe', 'Œ' => 'oe', 'æ' => 'ae', 'Æ' => 'ae', 'ß' => 'ss',
        '’' => "'", '‘' => "'",
    );
    $text = strtr($text, $map);
    $text = strtolower($text);
    // Collapse any remaining non ascii-letter/digit char (except apostrophe & dash) into a space
    $text = preg_replace('/[^a-z0-9\'-]+/', ' ', $text);
    return trim(preg_replace('/ +/', ' ', $text));
}

/**
 * Split a comma separated list of stop configs, ignoring commas inside braces:
 * "1{A,B},2,3{C}" => ["1{A,B}", "2", "3{C}"]
 */
function split_stop_configs($list)
{
    $list = trim((string) $list);
    if ($list === '') {
        return array();
    }
    $parts = preg_split('/,(?![^{]*\})/', $list);
    return array_values(array_filter(array_map('trim', $parts), 'strlen'));
}

/**
 * Parse a stop configuration string "stopId" or "stopId{lineId,lineId}".
 * @return array|null [stopId, allowedLines|null]
 */
function parse_stop_config($stopIdConfig)
{
    if (!preg_match('/^([^{]+)(?:\{(.*)\})?$/', $stopIdConfig, $m)) {
        return null;
    }
    $allowed = (isset($m[2]) && $m[2] !== '') ? explode(',', $m[2]) : null;
    return array($m[1], $allowed);
}

/**
 * Resolve a list of stop configs ("id{lines}" strings) into stop descriptors.
 * @return array list of ['id', 'name', 'city', 'line_ids', 'lines', 'allowed_lines']
 */
function resolve_stops($stopIdConfigs)
{
    $stops = load_stops();
    $lines = load_lines();
    $result = array();
    foreach ($stopIdConfigs as $config) {
        $parsed = parse_stop_config(trim($config));
        if (!$parsed) {
            continue;
        }
        list($stopId, $allowed) = $parsed;
        if (!isset($stops[$stopId])) {
            continue;
        }
        $row = $stops[$stopId];
        $lineIds = array();
        foreach ($row[2] as $lineId) {
            if ($allowed === null || in_array($lineId, $allowed, true)) {
                $lineIds[] = $lineId;
            }
        }
        $result[] = array(
            'id' => (string) $stopId,
            'name' => $row[0],
            'city' => $row[1],
            'line_ids' => $lineIds,
            'lines' => array_values(array_filter(array_map(function ($id) use ($lines) {
                return isset($lines[$id]) ? $lines[$id] : null;
            }, $lineIds))),
            'allowed_lines' => $allowed,
        );
    }
    return $result;
}

/** Send a JSON response and exit. */
function json_response($data, $status = 200)
{
    http_response_code($status);
    header('Content-Type: application/json; charset=utf-8');
    header('Cache-Control: no-store');
    echo json_encode($data, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
    exit;
}

/** Escape text for HTML output. */
function e($text)
{
    return htmlspecialchars((string) $text, ENT_QUOTES, 'UTF-8');
}
